version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flightdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  refresher:
    image: postgres:13
    depends_on:
      - postgres
    command: >
      bash -c "while true; do
        PGPASSWORD=postgres psql -h postgres -U postgres -d flightdb -c 'REFRESH MATERIALIZED VIEW popular_routes;';
        sleep 3600;
      done"

  metabase:
    image: metabase/metabase  # Версия с работающими линейными картами
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase_db
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: postgres
      MB_ENABLE_EXPERIMENTAL_FEATURES: "true"
      MB_LINE_MAPS_ENABLED: "true"
    volumes:
      # Добавляем кастомные картографические стили
      - ./metabase/maps:/metabase-data/maps

  monitor:
    build: ./app
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
    volumes:
      - ./app:/app

volumes:
  postgres_data: